# === Netlify Build Settings ===
[build]
command = "chmod +x netlify-force-install.sh && ./netlify-force-install.sh"  # Runs your custom install + build script
publish = "dist"                         # The folder to deploy (must match your build output)

# === Environment Variables ===
[build.environment]
NODE_VERSION = "18.17.1"
NPM_FLAGS = "--legacy-peer-deps --force"  # Useful for tricky dependency graphs

# === Redirects for SPA Routing ===
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
